### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by miekg** [AlessandroSechi/zammad-go#9]
See https://docs.zammad.org/en/latest/api/intro.html#pagination

Probably nicest to do this implicit, and make the API just gather all JSON and return a giant list; downside is that this will cost a memory, OTOH what woud be large ? total number of ticket and/or per ticket articles

**Comment by AlessandroSechi** [comment]
What if we implement `Next()`  method with proper receiver?
We should store `per_page`, `sort_ by` and `order_by` (so ordering is coherent) so user of library can just call `Next()` and get next page of results. We could also add a `FetchAll()` to fetch all list as you suggested, which will just use `Next()` under the hood to retrive whole list.

**Comment by miekg** [comment]
`Next()` is a nice idea!

**Comment by AlessandroSechi** [comment]
Ok, will take care of that
